"""
Mock Service for Case Co-Pilot

Simulates final CSV output as generated by the full AI + utility pipeline.
This output matches Rally-compatible import format exactly.

Used when USE_MOCK_LLM=true.
"""

import time


def generate_testcases(
    story_id: str,
    criteria: str,
    test_type: str,
    email: str
) -> str:
    """
    Generate mock Rally-compatible CSV test cases.

    This function intentionally mirrors the FINAL output format
    expected by the frontend and Rally import.

    Parameters
    ----------
    story_id : str
        Rally User Story ID
    criteria : str
        Acceptance criteria text
    test_type : str
        Functional / UAT / Regression
    email : str
        Owner email

    Returns
    -------
    str
        Rally-compatible CSV string
    """

    # Simulate processing delay (UI loader testing)
    time.sleep(3)

    owner_email = email if email else "mock.owner@company.com"
    story_ref = story_id if story_id else "US-MOCK-001"

    # --- CSV HEADER (FINAL FORMAT) ---
    csv_headers = (
        "Object Type,Name,Description,Owner,Type,Method,Work Product\n"
    )

    # --- MOCK ROWS ---
    csv_rows = (
        # Positive Scenario
        f'Test Case,TC-{story_ref}-001: Positive Flow,'
        f'Verify main success path using criteria snippet: "{criteria[:40]}...",'
        f'{owner_email},{test_type},Manual,{story_ref}\n'

        # Negative Scenario
        f'Test Case,TC-{story_ref}-002: Negative - Invalid Input,'
        f'Verify handling of incorrect, empty, or invalid inputs,'
        f'{owner_email},{test_type},Manual,{story_ref}\n'

        # Edge Case Scenario
        f'Test Case,TC-{story_ref}-003: Edge Case - Boundary Conditions,'
        f'Validate system behavior for edge or boundary scenarios,'
        f'{owner_email},{test_type},Manual,{story_ref}\n'
    )

    return csv_headers + csv_rows
