# backend/agents.py
import os
import json
from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import List

# Load environment variables (e.g., OPENAI_API_KEY)
load_dotenv()

# --- Configuration ---
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.3)  # Using a capable, cost-effective model


# --- 1. Define the Agent Output Structure (JSON Schema) ---
# This schema tells the AI exactly what fields to output for a single test case.
class TestCase(BaseModel):
    """A Pydantic model for a single test case scenario generated by the AI."""
    Name: str = Field(
        description="A brief, descriptive name for the test case, e.g., 'Verify successful login with valid credentials'.")
    Description: str = Field(
        description="The detailed description of the scenario, including any background information or setup.")
    Steps: str = Field(description="The numbered, actionable steps to execute the test case.")
    Expected_Result: str = Field(
        description="The precise, verifiable outcome the system must achieve to pass the test.")


class TestCaseList(BaseModel):
    """The final list structure for the agent's output."""
    scenarios: List[TestCase]


# --- 2. The Core Patching and CSV Conversion Function ---
def patch_and_format_to_csv(raw_json_output: str, story_id: str, criteria: str, test_type: str, email: str) -> str:
    """
    Patches the AI-generated scenarios with user input fields and converts the final list to a CSV string.
    """
    try:
        # Load the JSON from the AI (validated by the Pydantic model)
        parsed_data = TestCaseList.parse_raw(raw_json_output)
    except Exception as e:
        # Fallback if the AI fails to produce perfect JSON
        print(f"Failed to parse AI JSON output: {e}. Output was: {raw_json_output[:200]}...")
        # In a real system, you might ask the AI to re-run or use a correction agent.
        raise ValueError("AI Agent failed to format test cases correctly.")

    # Define the final CSV headers
    headers = "Object Type,Name,Description,Owner,Type,Method,Workproduct\n"
    csv_rows = []

    # Iterate through the AI-generated scenarios and patch the data
    for tc in parsed_data.scenarios:
        # Combine Description, Steps, and Expected Result into one large field for Rally's Description
        # This keeps the AI's output detailed but fits the final CSV columns.
        full_description = (
            f"**Criteria:** {criteria}\n"
            f"**Description:** {tc.Description}\n\n"
            f"**Steps:**\n{tc.Steps}\n\n"
            f"**Expected Result:**\n{tc.Expected_Result}"
        ).replace('\n', ' ').replace(',', ';')  # Replace newlines and commas to keep CSV integrity

        # Define the fixed/patched fields from user input
        patched_fields = {
            "Object Type": "Test Case",
            "Name": tc.Name,
            "Description": full_description,
            "Owner": email if email else "AI.Generated@company.com",  # Use a default if email is blank
            "Type": test_type,
            "Method": "Manual",
            "Workproduct": story_id
        }

        # Format the fields into a CSV line (order matters!)
        row = (
            f'"{patched_fields["Object Type"]}",'
            f'"{patched_fields["Name"]}",'
            f'"{patched_fields["Description"]}",'
            f'"{patched_fields["Owner"]}",'
            f'"{patched_fields["Type"]}",'
            f'"{patched_fields["Method"]}",'
            f'"{patched_fields["Workproduct"]}"'
        )
        csv_rows.append(row)

    return headers + "\n".join(csv_rows)


# --- 3. The Crew Orchestration Function ---
def run_test_case_crew(story_id: str, criteria: str, test_type: str, email: str) -> str:
    # --- AGENT 1: QA Strategist ---
    qa_strategist = Agent(
        role='Expert QA Lead and Agile Strategist',
        goal=f'Analyze the Acceptance Criteria for {story_id} and develop a comprehensive set of test scenarios covering positive, negative, and edge cases for {test_type} testing.',
        backstory="You are a 15-year veteran QA Lead who translates ambiguous requirements into actionable test scenarios.",
        verbose=True,  # Set to True to see the thought process in the console
        allow_delegation=False,
        llm=llm
    )

    # --- AGENT 2: JSON Formatter ---
    json_formatter = Agent(
        role='Precise Data Formatter',
        goal='Strictly convert the test scenarios into a valid JSON list based on the provided TestCaseList schema.',
        backstory="You are an expert data serialization specialist. Your only job is to ensure the output is perfectly formed JSON.",
        verbose=False,
        allow_delegation=False,
        llm=llm
    )

    # --- TASK 1: Analysis & Scenario Generation ---
    analysis_task = Task(
        description=f"""
        User Story ID: {story_id}
        Test Type: {test_type}
        Acceptance Criteria to analyze:
        ---
        {criteria}
        ---

        Generate a minimum of 4 distinct test scenarios (positive, negative, and edge cases). 
        The final output must be structured for the JSON Formatter Agent.
        """,
        agent=qa_strategist,
        expected_output="A detailed plan or structured list of scenarios for the Formatter Agent."
    )

    # --- TASK 2: Final JSON Formatting ---
    formatting_task = Task(
        description="Take the test scenarios provided by the QA Strategist and strictly format them into a single JSON object that conforms to the TestCaseList Pydantic schema.",
        agent=json_formatter,
        context=[analysis_task],
        output_json=TestCaseList,  # CRITICAL: Enforce the Pydantic schema for the output
        expected_output="A raw JSON string adhering to the TestCaseList schema."
    )

    # --- CREW SETUP & KICKOFF ---
    crew = Crew(
        agents=[qa_strategist, json_formatter],
        tasks=[analysis_task, formatting_task],
        process=Process.sequential
    )

    raw_json_result = crew.kickoff()

    # --- POST-PROCESSING: Patching and CSV Conversion ---
    final_csv = patch_and_format_to_csv(
        raw_json_result,
        story_id,
        criteria,
        test_type,
        email
    )

    return final_csv